### ISSUE TITLE
Minimum required CMake version

### ISSUE THREAD

**Issue by tbeu** [alexreinking/so69978314#1]
Hi, coming from https://stackoverflow.com/a/72341403/8520615 , could the minimum required CMake version be relaxed to 3.21 (instead of 3.22)? Thanks!

**Comment by alexreinking** [comment]
Sorry, but no. I am adamantly opposed to supporting old versions of CMake and I will not update both my SO answer and this repository in contradiction with that viewpoint.

However, I appreciate the time you took to ask. Therefore, I have licensed this code under the MIT license. Under that license, you may fork this repository and modify what you wish.

**Comment by tbeu** [comment]
Understandable. I only was wondering why it is 3.22, since both TARGET_RUNTIME_DLLS and PROJECT_IS_TOP_LEVEL are available with 3.21 and it is not obvious which of the other features requires 3.22.
